import { LSK001, API_CONFIG } from './config.js';
import { LSK_SEGMENTS } from './data/lskSegments.js';
import { getCrowdData } from './services/crowdApi.js';
import { getCountdown, secondsRemaining } from './services/countdownApi.js';
import { getWeather } from './services/weatherApi.js';
import { getRainForecast } from './services/rainForecast.js';
const $ = selector => document.querySelector(selector);
let countdown; let crowdData = []; let map;
const labels = { low: '低', medium: '中', high: '高', unknown: '未能推算' };
function ageLabel(updatedAt) { const seconds = Math.max(0, (Date.now() - Date.parse(updatedAt)) / 1000); return seconds < 90 ? '🟢 剛更新' : seconds <= API_CONFIG.staleAfterSeconds ? `🟡 資料約 ${Math.ceil(seconds / 60)} 分鐘前` : '🔴 資料較舊'; }
function initMap() { if (!globalThis.L) return; map = L.map('map', { zoomControl: false }).setView([LSK001.lat, LSK001.lng], 16); L.control.zoom({ position: 'bottomright' }).addTo(map); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '© OpenStreetMap contributors' }).addTo(map); const icon = L.divIcon({ className: 'lsk-marker', html: '<span>🚦</span><b>LSK001</b>', iconSize: [82, 42], iconAnchor: [41, 42] }); L.marker([LSK001.lat, LSK001.lng], { icon }).addTo(map).bindPopup(`<b>🚦 LSK001</b><br>${LSK001.name}<br><small>${LSK001.coordinateStatus}</small>`); }
function renderCountdown() { if (!countdown) return; const seconds = secondsRemaining(countdown.endTime); $('#countdownSeconds').textContent = `${seconds} 秒`; $('#signalState').textContent = countdown.state === 'green' ? '綠燈' : '紅燈'; $('#signalLight').className = `signal-light ${countdown.state}`; const mock = countdown.status !== 'live'; $('#countdownSource').className = `source-chip ${mock ? 'mock' : 'live'}`; $('#countdownSource').textContent = countdown.source; $('#countdownStatus').textContent = mock ? '開發示範倒數 · 非即時' : '即時資料'; if (seconds <= 1) syncCountdown(); }
async function syncCountdown() { countdown = await getCountdown(); renderCountdown(); }
function segmentTemplate(segment) { const data = crowdData.find(item => item.roadSegmentId === segment.roadSegmentId); if (!data) return `<button class="segment unknown" data-segment="${segment.roadSegmentId}"><i></i><span><b>${segment.name}</b><small>目前沒有足夠的人流訊號</small></span><em>未連線</em></button>`; const score = data.flowScore === null ? '—' : `${data.flowScore} / 100`; return `<button class="segment ${data.flowLevel}" data-segment="${segment.roadSegmentId}"><i></i><span><b>${data.name}</b><small>推算人流：${labels[data.flowLevel]} · ${ageLabel(data.updatedAt)}</small></span><em>${score}</em></button>`; }
function renderSegments() { $('#segmentList').innerHTML = LSK_SEGMENTS.map(segmentTemplate).join(''); document.querySelectorAll('[data-segment]').forEach(button => button.addEventListener('click', () => showSegment(button.dataset.segment))); }
function showSegment(id) { const segment = crowdData.find(item => item.roadSegmentId === id); if (!segment) { alert('人流資料暫未連線。這不是 Google 即時行人數。'); return; } const confidence = segment.confidence >= .7 ? '高' : segment.confidence >= .45 ? '中' : '低'; alert(`${segment.name}\n\n推算人流：${labels[segment.flowLevel]}\nFlow Score：${segment.flowScore} / 100\n資料來源：Outscraper Google Maps Popular Times\n參考地點：${segment.sourceCount}\n推算可信度：${confidence}\n資料更新：${ageLabel(segment.updatedAt)}\n\n推算人流並非實際行人計數。`); }
async function loadCrowd() { try { crowdData = await getCrowdData(); $('#crowdStatus').textContent = 'OUTSCRAPER LIVE DATA'; $('#crowdStatus').className = 'data-status live'; $('#crowdSummary').textContent = `推算人流：${labels[crowdData[0]?.flowLevel] || '未能推算'}`; } catch { crowdData = []; $('#crowdStatus').textContent = '人流資料暫未連線'; $('#crowdStatus').className = 'data-status offline'; $('#crowdSummary').textContent = '推算人流：資料暫未連線'; } renderSegments(); $('#diagnosticOutput').textContent = JSON.stringify({ endpoint: API_CONFIG.crowdUrl, receivedSegments: crowdData.length, rawSignals: crowdData.reduce((n, item) => n + item.signals.length, 0), segments: crowdData.map(item => ({ roadSegmentId: item.roadSegmentId, flowScore: item.flowScore, confidence: item.confidence, updatedAt: item.updatedAt, signals: item.signals.map(signal => ({ name: signal.name, distanceMeters: signal.distanceMeters, livePercentage: signal.livePercentage, distanceWeight: signal.distanceWeight, typeWeight: signal.typeWeight, finalWeight: signal.finalWeight })) })), note: crowdData.length ? 'Worker live response. Weights are diagnostic only, not a claim of actual pedestrian counts.' : 'No response. API key remains server-side in OUTSCRAPER_API_KEY.' }, null, 2); }
async function loadWeather() { const weather = await getWeather(); const rain = await getRainForecast(); $('#weatherMessage').textContent = weather.status === 'unavailable' ? weather.message : `${weather.temperature}° · ${weather.condition}`; $('#rainForecast').textContent = rain.status === 'unavailable' ? rain.message : ''; }
function locate() { if (!navigator.geolocation) return; $('#locationMessage').textContent = '正在取得位置…'; navigator.geolocation.getCurrentPosition(({ coords }) => { const meters = Math.round(Math.hypot((coords.latitude - LSK001.lat) * 111000, (coords.longitude - LSK001.lng) * 102000)); $('#routeDistance').textContent = `${meters} m`; $('#routeTime').textContent = `${Math.max(1, Math.ceil(meters / 75))} 分鐘`; $('#locationMessage').textContent = '已使用直線距離估算；位置只在這部裝置記憶體內使用。'; }, () => $('#locationMessage').textContent = '未能取得位置，沒有儲存任何位置資料。'); }
function openPanel(name) { ['weather', 'route'].forEach(key => $(`#${key}Panel`).hidden = key !== name); document.querySelectorAll('.tab').forEach(tab => tab.classList.toggle('active', tab.dataset.panel === name)); }
initMap(); renderSegments(); syncCountdown(); loadCrowd(); loadWeather(); setInterval(renderCountdown, 250); setInterval(loadCrowd, API_CONFIG.crowdRefreshMs); document.addEventListener('visibilitychange', () => { if (!document.hidden) { syncCountdown(); loadCrowd(); } }); $('#locateButton').onclick = locate; document.querySelectorAll('.tab').forEach(tab => tab.onclick = () => openPanel(tab.dataset.panel)); $('#diagnosticButton').onclick = () => $('#diagnosticPanel').hidden = false; document.querySelectorAll('[data-close]').forEach(button => button.onclick = () => button.closest('.sheet, .diagnostic-panel').hidden = true); if ('serviceWorker' in navigator) addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js'));
